Ds 3465
Displayr/flipData pull request #16
Opened 2021-08-08 23:54 UTC by TimBock

2021-08-08 23:55 UTC, TimBock commented
This blocks some work for core: RS-8148

2021-08-09 08:35 UTC, mwmclean commented on R/calibrate.R
> +        subset <- rep(TRUE, nrow(adjustment.variables))
Should this be `NROW` as in numericTargets (Line 179)?

2021-08-10 00:26 UTC, mwmclean requested changes

2021-08-10 04:41 UTC, mwmclean commented on R/weightingdialog.R
> +#'
Extra whitespace.

2021-08-10 04:41 UTC, mwmclean commented on R/weightingdialog.R
> +
Can we add more `@details` to further explain the differences between this function and `Calibrate`?

2021-08-10 04:41 UTC, mwmclean commented on R/weightingdialog.R
> +WeightingDialog <- function(categorical.variables = NULL,
Will this code ever be viewed/edited in the R Code editor in Displayr? If so, is there a better name for this function without the word "Dialog"? (Similarly, for `computeWeightsDialog`).

2021-08-10 09:21 UTC, mwmclean approved these changes

2021-08-10 09:24 UTC, merged